USE [master]
GO
/****** Object:  Database [prodraftdb]    Script Date: 1/5/2025 10:06:43 ******/
CREATE DATABASE [prodraftdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prodraftdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLDEVELOPERPR\MSSQL\DATA\prodraftdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'prodraftdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLDEVELOPERPR\MSSQL\DATA\prodraftdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [prodraftdb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [prodraftdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [prodraftdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [prodraftdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [prodraftdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [prodraftdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [prodraftdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [prodraftdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [prodraftdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [prodraftdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [prodraftdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [prodraftdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [prodraftdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [prodraftdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [prodraftdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [prodraftdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [prodraftdb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [prodraftdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [prodraftdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [prodraftdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [prodraftdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [prodraftdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [prodraftdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [prodraftdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [prodraftdb] SET RECOVERY FULL 
GO
ALTER DATABASE [prodraftdb] SET  MULTI_USER 
GO
ALTER DATABASE [prodraftdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [prodraftdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [prodraftdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [prodraftdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [prodraftdb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [prodraftdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'prodraftdb', N'ON'
GO
ALTER DATABASE [prodraftdb] SET QUERY_STORE = ON
GO
ALTER DATABASE [prodraftdb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [prodraftdb]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 1/5/2025 10:06:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](255) NOT NULL,
	[apellidos] [nvarchar](255) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[contraseña] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[contraseña] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category_players]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category_players](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_player] [int] NOT NULL,
	[id_category] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category_sport]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category_sport](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_sport] [int] NOT NULL,
	[img] [nvarchar](255) NOT NULL,
	[nombre] [nvarchar](255) NOT NULL,
	[reglas] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Deporte]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Deporte](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](255) NOT NULL,
	[cloudinary_id] [nvarchar](255) NULL,
	[url] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Entrenador]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Entrenador](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[contraseña] [nvarchar](255) NOT NULL,
	[nombres] [nvarchar](255) NOT NULL,
	[fechaNacimiento] [date] NOT NULL,
	[id_sport] [int] NOT NULL,
	[descripcion] [nvarchar](max) NULL,
	[cloudinary_id] [nvarchar](255) NULL,
	[url] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[contraseña] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Jugador]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jugador](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[contraseña] [nvarchar](255) NOT NULL,
	[nombres] [nvarchar](255) NOT NULL,
	[apellidos] [nvarchar](255) NOT NULL,
	[fechaNacimiento] [date] NOT NULL,
	[codigo] [int] NOT NULL,
	[grado] [nvarchar](50) NOT NULL,
	[seccion] [nvarchar](50) NOT NULL,
	[createdAt] [datetime] NULL,
	[status_img_academic] [nvarchar](255) NULL,
	[status_img_conduct] [nvarchar](255) NULL,
	[status_sport] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[contraseña] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Observaciones_Entrenador]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Observaciones_Entrenador](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_admin] [int] NOT NULL,
	[id_entrenador] [int] NOT NULL,
	[observacion] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Observaciones_Jugador]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Observaciones_Jugador](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_atleta] [int] NOT NULL,
	[observacion] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rubric_fields]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rubric_fields](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[description] [nvarchar](max) NOT NULL,
	[max_puntaje] [int] NOT NULL,
	[nombre] [nvarchar](255) NOT NULL,
	[id_sport] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rubric_Score_player]    Script Date: 1/5/2025 10:06:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rubric_Score_player](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[puntaje] [int] NOT NULL,
	[id_player] [int] NOT NULL,
	[id_rubric_field] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Deporte] ADD  DEFAULT ('') FOR [cloudinary_id]
GO
ALTER TABLE [dbo].[Deporte] ADD  DEFAULT ('') FOR [url]
GO
ALTER TABLE [dbo].[Entrenador] ADD  DEFAULT ('') FOR [descripcion]
GO
ALTER TABLE [dbo].[Entrenador] ADD  DEFAULT ('') FOR [cloudinary_id]
GO
ALTER TABLE [dbo].[Entrenador] ADD  DEFAULT ('') FOR [url]
GO
ALTER TABLE [dbo].[Jugador] ADD  DEFAULT (getdate()) FOR [createdAt]
GO
ALTER TABLE [dbo].[Category_players]  WITH CHECK ADD FOREIGN KEY([id_category])
REFERENCES [dbo].[Category_sport] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Category_players]  WITH CHECK ADD FOREIGN KEY([id_player])
REFERENCES [dbo].[Jugador] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Category_sport]  WITH CHECK ADD FOREIGN KEY([id_sport])
REFERENCES [dbo].[Deporte] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Entrenador]  WITH CHECK ADD FOREIGN KEY([id_sport])
REFERENCES [dbo].[Deporte] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Observaciones_Entrenador]  WITH CHECK ADD FOREIGN KEY([id_admin])
REFERENCES [dbo].[Admin] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Observaciones_Entrenador]  WITH CHECK ADD FOREIGN KEY([id_entrenador])
REFERENCES [dbo].[Entrenador] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Observaciones_Jugador]  WITH CHECK ADD FOREIGN KEY([id_atleta])
REFERENCES [dbo].[Jugador] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Rubric_fields]  WITH CHECK ADD FOREIGN KEY([id_sport])
REFERENCES [dbo].[Deporte] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Rubric_Score_player]  WITH CHECK ADD FOREIGN KEY([id_player])
REFERENCES [dbo].[Jugador] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Rubric_Score_player]  WITH CHECK ADD FOREIGN KEY([id_rubric_field])
REFERENCES [dbo].[Rubric_fields] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
USE [master]
GO
ALTER DATABASE [prodraftdb] SET  READ_WRITE 
GO
